### ISSUE TITLE
Embedding add document to store not working with url

### ISSUE THREAD

**Issue by rateeshsubramanian** [MuleSoft-AI-Chain-Project/mac-vectors#7]
Hi Team,

I tried Embedding add document to store with url but its giving me a null url error.

`ERROR 2024-08-08 21:57:06,161 [[MuleRuntime].uber.02: [mulechain_upgrade_kb].mulechain_upgrade_kbFlow.CPU_LITE @1395e877] [processor: mulechain_upgrade_kbFlow/processors/0; event: 54569cf0-55c7-11ef-b63c-00249b37b092] org.mule.runtime.core.privileged.exception.DefaultExceptionListener: 
********************************************************************************
Message               : url cannot be null
Element               : mulechain_upgrade_kbFlow/processors/0 @ mulechain_upgrade_kb:mulechain_upgrade_kb.xml:15 (Embedding add document to store)
Element DSL           : <mulechain-vectors:embedding-add-document-to-store doc:name="Embedding add document to store" doc:id="be875750-d8ab-4765-bed9-82cd1cd5a11d" config-ref="MuleChain_Vectors_Config" fileType="#[payload.type1]" storeName="java-17-upgrade-kb" contextPath="#[payload.path]" maxSegmentSizeInChars="1000" maxOverlapSizeInChars="200"></mulechain-vectors:embedding-add-document-to-store>
Error type            : MULE:UNKNOWN
FlowStack             : at mulechain_upgrade_kbFlow(mulechain_upgrade_kbFlow/processors/0 @ mulechain_upgrade_kb:mulechain_upgrade_kb.xml:15 (Embedding add document to store))
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.IllegalArgumentException: url cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37)
	at dev.langchain4j.data.document.source.UrlSource.<init>(UrlSource.java:21)
	at dev.langchain4j.data.document.source.UrlSource.from(UrlSource.java:44)
	at dev.langchain4j.data.document.loader.UrlDocumentLoader.load(UrlDocumentLoader.java:21)
	at com.mule.mulechain.vectors.internal.MuleChainVectorsOperations.addFileEmbedding(MuleChainVectorsOperations.java:565)
	`

This is how the flow is 
![image](https://github.com/user-attachments/assets/b16aaf74-1911-4e2b-bb47-f9e724c64b6b)

and I am passing input as below
```{
    "path" : "https%3A%2F%2Fmulechain.ai%2Fdocs%2Fmulechain-ai%2Fconnector-overview",
    "type1":"url"
}```

have also tried without url encoding but getting the same error.

**Comment by amirkhan-ak-sf** [comment]
@rateeshsubramanian sorry, for the late reply. 

Is it just for URL or also for `text` and `any` time?

I see you are trying this URL:
`"path" : "https%3A%2F%2Fmulechain.ai%2Fdocs%2Fmulechain-ai%2Fconnector-overview",`

could you try this URL please: `https://mac-project.ai/docs/mulechain-ai/connector-overview`

**Comment by amirkhan-ak-sf** [comment]
Also tested it 
<img width="704" alt="image" src="https://github.com/user-attachments/assets/b8177b79-4cfb-490d-b281-98c5405bd336">

**Comment by rateeshsubramanian** [comment]
Hi @amirkhan-ak-sf ,

Text is working fine, I have provided the contextPath and fileType directly in connector as below and teste it and its working fine.
![image](https://github.com/user-attachments/assets/13e372bc-343c-4cd1-a2d9-ebb685586389)

But for url and any, when I pass the url in contextPath as below, I am getting Error
![image](https://github.com/user-attachments/assets/db6ce389-be93-427b-80e2-bb3bb738afbf)

Below is the error:
ERROR 2024-08-19 17:42:11,947 [[MuleRuntime].uber.02: [mulechain_upgrade_kb].mulechain_upgrade_kbFlow.CPU_LITE @23bb045d] [processor: mulechain_upgrade_kbFlow/processors/0; event: fb114010-5e49-11ef-8fe2-00249b37b092] org.mule.runtime.core.privileged.exception.DefaultExceptionListener: 
********************************************************************************
Message               : Illegal char <:> at index 5: https://mac-project.ai/docs/mulechain-ai/connector-overview
Element               : mulechain_upgrade_kbFlow/processors/0 @ mulechain_upgrade_kb:mulechain_upgrade_kb.xml:16 (Embedding add document to store)
Element DSL           : <mulechain-vectors:embedding-add-document-to-store doc:name="Embedding add document to store" doc:id="be875750-d8ab-4765-bed9-82cd1cd5a11d" config-ref="MuleChain_Vectors_Config" storeName="Mac" contextPath="https://mac-project.ai/docs/mulechain-ai/connector-overview" maxSegmentSizeInChars="1000" maxOverlapSizeInChars="200" fileType="url"></mulechain-vectors:embedding-add-document-to-store>
Error type            : MULE:UNKNOWN
FlowStack             : at mulechain_upgrade_kbFlow(mulechain_upgrade_kbFlow/processors/0 @ mulechain_upgrade_kb:mulechain_upgrade_kb.xml:16 (Embedding add document to store))
--------------------------------------------------------------------------------
Root Exception stack trace:
java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://mac-project.ai/docs/mulechain-ai/connector-overview
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.mule.mulechain.vectors.internal.MuleChainVectorsOperations.addFileEmbedding(MuleChainVectorsOperations.java:534)
	at com.mule.mulechain.vectors.internal.MuleChainVectorsOperations$addFileEmbedding$MethodComponentExecutor_mulechain_upgrade_kb.execute(Unknown Source)
	at org.mule.runtime.module.extension.internal.runtime.execution.GeneratedMethodComponentExecutor.execute(GeneratedMethodComponentExecutor.java:94)
	at org.mule.runtime.module.extension.internal.runtime.execution.CompletableMethodOperationExecutor.doExecute(CompletableMethodOperationExecutor.java:26)
	at org.mule.runtime.module.extension.internal.runtime.execution.AbstractCompletableMethodOperationExecutor.execute(AbstractCompletableMethodOperationExecutor.java:61)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeCommand(DefaultExecutionMediator.java:254)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeWithInterceptors(DefaultExecutionMediator.java:237)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$execute$1(DefaultExecutionMediator.java:144)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$new$0(DefaultExecutionMediator.java:80)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.withExecutionTemplate(DefaultExecutionMediator.java:335)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.execute(DefaultExecutionMediator.java:143)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.executeOperation(ComponentMessageProcessor.java:578)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.prepareAndExecuteOperation(ComponentMessageProcessor.java:822)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.access$100(ComponentMessageProcessor.java:189)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$4.lambda$innerEventDispatcher$6(ComponentMessageProcessor.java:681)
	at reactor.core.* (6 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$onEvent$13(ComponentMessageProcessor.java:446)
	at org.mule.runtime.core.internal.policy.DefaultPolicyManager.lambda$static$0(DefaultPolicyManager.java:85)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.onEvent(ComponentMessageProcessor.java:457)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$createOuterFlux$6(ComponentMessageProcessor.java:398)
	at reactor.core.* (3 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at org.mule.runtime.core.privileged.processor.chain.* (2 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at reactor.core.* (10 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:180)
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

********************************************************************************

Thanks,

**Comment by amirkhan-ak-sf** [comment]
Hi @rateeshsubramanian 

the any type is only for files so the URL error is fine on the type `any`. 
Can you download the connector again from the [master branch](https://github.com/MuleSoft-AI-Chain-Project/mac-vectors) and change the version in the pom.xml to 0.1.1. and after than build the project again as described here: `https://mac-project.ai/docs/mulechain-vectors/getting-started` 

To change the version in the pom.xml, open the pom, local the XML tag `<version>0.1.0</version>` and update it to `<version>0.1.1</version>`. After you've installed the new version add the dependency in your mule app to 0.1.1 for the connector. 

Let me know the results. 

Thanks

**Comment by rateeshsubramanian** [comment]
Hi @amirkhan-ak-sf ,

Its working fine with version 0.1.1. 
Thanks!

**Comment by amirkhan-ak-sf** [comment]
Thats great! Thanks @rateeshsubramanian !!
